Allows HTTPS connections to the Solr instance.
PTCInc/solr-php-client pull request #2
Opened 2016-11-03 14:38 UTC by damienmckenna

Use the optional fifth argument to Apache_Solr_Service::__construct() in order to make a https connection to the Solr instance instead of it being hardcoded to http.

2016-11-03 16:32 UTC, djimenez requested changes
Will any of the transports need changed? doesn't seem like it, but wondering which transport you had actively used with this change.

2016-11-03 16:32 UTC, djimenez commented on Apache/Solr/Service.php
> +    if (empty($protocol))
tabs vs spaces issue

2016-11-03 21:13 UTC, damienmckenna commented
Just so you know, I ended up using an overridden class in the ApacheSolr module for Drupal 6 to achieve the results I wanted (see https://www.drupal.org/node/2824643). That module is written against commit 25183a9, which is a bit out of date, so I wasn't able to fully test this PR.

2016-11-19 02:42 UTC, djimenez commented
commit merged with whitespace and phpdoc changes as well as making check for empty throw an exception, similar to setHost.

See ecc04b5

2016-11-19 02:42 UTC, closed without merging

2016-11-19 03:40 UTC, damienmckenna commented
Thanks :-)